//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CurrentElementTally.h
//  @ Date : 1/31/2014
//  @ Author : 
//
//


#if !defined(_CURRENTELEMENTTALLY_H)
#define _CURRENTELEMENTTALLY_H

#include "ElementTally.h"

class CurrentElementTally : public ElementTally
{
public:
	CurrentElementTally();
	CurrentElementTally(int n_angular_bins, int n_spatial_moments);
	virtual void incrementScore(double weight, double path_length, double normal_cosine,
		double volume, double normalized_position);
	
};

#endif  //_CURRENTELEMENTTALLY_H
