// Continuous Weight Deposition particles for pure absorber problems, this particle does not undergo absorption.  The weight
// of the particle is attenuated exponentially.  The only changes to the base Particle
// class is in the way that tallies are calculated and the histories are ran.  After
// attenuating a certain number of MFP the particle switches to a analog transport and
// calls the base class routines.  
//
//  Generated by StarUML(tm) C++ Add-In
//
//  
//  @ File Name : CWDParticle1D.h
//  @ Date : 03/14/2014
//  @ Author : Simon R Bolding
//
//

#if !defined(_CWDPARTICLE1D_H)
#define _CWDPARTICLE1D_H

#include "Particle1D.h"
#include <iostream>
#include <cmath>

class CWDParticle1D : public Particle1D
{
private:

	bool _is_analog; //particle is in analog transport mode if true
	double _non_analog_mfp; //how many mfp to stream in continous wgt deposition mode

public:
	
	CWDParticle1D(HoMesh* mesh, Source* src, RNG* rng, string method_str); //default constructor
	virtual void runHistory();
	virtual void scoreElementTally(double path_start_mfp, double path_end_mfp); //passed where the track begin and ended, in terms of x-coordinate
};





#endif //_CWDPARTICLE1D_H
