//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ECMCTally.h
//  @ Date : 2/10/2014
//  @ Author : 
//
//


#if !defined(_ECMCTALLY_H)
#define _ECMCTALLY_H

#include "CurrentElementTally.h"
#include "FluxElementTally.h"
#include <vector>

class ECMCTally
{
protected:
	CurrentElementTally _angular_moment;
	FluxElementTally _spatial_moments;
public:
	ECMCTally(); //default constructor, will initialize the spatial moments
	~ECMCTally(); //this gets called when mesh is refined because parent classes do not score tallies

	void incrementScores(double weight, double path_length, double normalized_dir_cosine, 
		double volume, double normalized_position); //Using a normalized dir_cosine produces an always positive value for moment
	std::vector<double> getSpatialMoments(int n_histories); //return the score for the spatial moment
	double getAngularMoment(int n_histories); //return the score for angular moment
	void reset(); //reset all values to zero
};

#endif  //_ECMCTALLY_H
