//  This is for solving the 1D problem
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LoSolver1D.h
//  @ Date : 11/1/2013
//  @ Author : 
//
//


#if !defined(_LOSOLVER1D_H)
#define _LOSOLVER1D_H

#include "LoSolver.h"
#include "numMatrixBanded.h"

class LoSolver1D : public LoSolver
{
protected:
	
	//Functions
    virtual void assembleSystem();	//Build
	virtual void setNumDof();

public:

	//Public Functions
	LoSolver1D(Mesh* mesh); //Constructor, needs a mesh object to work with
	LoSolver1D();
	virtual void printSolution(std::ostream& out);
	virtual void solveSystem(); //can be overridden by derived classes
		//by default does a direct inversion of banded, fixed source
		//system.  All derived classes modify the base system through this 
		//function.
};

#endif  //_LOSOLVER1D_H
