//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : 1DNode.h
//  @ Date : 11/1/2013
//  @ Author : 
//
//


#if !defined(_1DNODE_H)
#define _1DNODE_H

#include "Node.h"

class Node1D : public Node
{
private:
	Node1D(); //default constructor, never used
public:
	Node1D(int id, double point);  //Just need location to create 1D node
	virtual void print(std::ostream &out);
};

#endif  //_1DNODE_H
