//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Node.h
//  @ Date : 11/1/2013
//  @ Author : 
//
//


#if !defined(_NODE_H)
#define _NODE_H
#include <ostream>


class Node
{
protected:
    int _id;
	double _x;
	double _y; //TODO not needed for 1D
	Node(); //Default construcotr, never used
public:
	Node(int id);
	virtual void print(std::ostream &out) = 0; //pure virtual, must implement in subclass
	double getX(void) const;
	double getY(void) const;
	int getID(void) const;
};

#endif  //_NODE_H
