//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : oneDMesh.h
//  @ Date : 11/1/2013
//  @ Author : 
//
//


#if !defined(_ONEDMESH_H)
#define _ONEDMESH_H

#include "Mesh.h"

class oneDMesh : public Mesh
{
public:
    int oneDMesh();
};

#endif  //_ONEDMESH_H
