//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : ElementTally.cpp
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#include "../include/ElementTally.h"

ElementTally::ElementTally(int n_angular_bins, int n_spatial_moments) : Tally(n_angular_bins, n_spatial_moments)
{

}


