//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : FaceTally.cpp
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#include "../include/FaceTally.h"

FaceTally::FaceTally(int n_angular_bins) : Tally(n_angular_bins, 1)
{

}