//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LoData.cpp
//  @ Date : 11/1/2013
//  @ Author : SRB
//
//

#include <stdlib.h>
#include "../include/LoData1D.h"
#include <iostream>

//Default Constructor
LoData1D::LoData1D():
_alpha(),
_surf_avg_cosines(),
_vol_avg_cosines()
{
	//initialize all the cosines to diffusion theory
	init();

	//For LD spatial closer alpha is 2
	_alpha = 2.0;
}

//for use by all constructors
void LoData1D::init()
{
	using LODATA_COSINES::STARTING_AVERAGE_COSINE;

	//Set average cosines all to 2/3 for diffusion theory 
	_vol_avg_cosines._mu_left_plus = STARTING_AVERAGE_COSINE ;
	_vol_avg_cosines._mu_left_minus = -STARTING_AVERAGE_COSINE ;
	_vol_avg_cosines._mu_right_plus = STARTING_AVERAGE_COSINE ;
	_vol_avg_cosines._mu_right_minus = -STARTING_AVERAGE_COSINE ;

	//Set average cosine values for surfaces/
	_surf_avg_cosines._mu_left_plus = STARTING_AVERAGE_COSINE ;
	_surf_avg_cosines._mu_left_minus = -STARTING_AVERAGE_COSINE ;
	_surf_avg_cosines._mu_right_plus = STARTING_AVERAGE_COSINE ;
	_surf_avg_cosines._mu_right_minus = -STARTING_AVERAGE_COSINE ;
}

double LoData1D::getSpatialClosureFactor() const
{
	return _alpha;
}

void LoData1D::setSpatialClosureFactor(double alpha)
{
	_alpha = alpha;
}

AveragedCosines LoData1D::getVolAveragedCos() const //Copy of data, not returning pointer
{
	return _vol_avg_cosines;
}

AveragedCosines LoData1D::getSurfAveragedCos() const
{
	return _surf_avg_cosines;
}

void LoData1D::setVolAveragedCos(AveragedCosines vol_avg_cosines)
{
	_vol_avg_cosines = vol_avg_cosines;
}

void LoData1D::setSurfAveragedCos(AveragedCosines surf_avg_cosines)
{
	_surf_avg_cosines = surf_avg_cosines;
}

//std::vector<double> LoData1D::getExtSourceNodalValues()
//{
//	return _ext_source_nodal_values;
//}
//
//void LoData1D::setExtSourceNodalValues(std::vector<double> ext_source_values)
//{
//	if (ext_source_values.size() != 2)
//	{
//		std::cerr << "Passed in the wrong size of vector to setExtSourceNodalvalues" << std::endl;
//		exit(1);
//	}
//	_ext_source_nodal_values = ext_source_values;
//}
